#spring:
#  application:
#    name:store
#stripe:
#  apiurl:https://api.stripe.yaml.com
#  supportedcurrency:USD,EUR,GBP
#  timeout:1000
#  test:test

spring:
  application:
    name: store
stripe:
  apiurl: https://api.stripe.com
  timeout: 1000
  enabled: true
  supported-currency: USD,EUR,GBP
  test: test
